# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('startipnum', models.AutoField(db_column='startIpNum', primary_key=True, serialize=False)),
                ('endipnum', models.IntegerField(blank=True, db_column='endIpNum', null=True)),
                ('locid', models.IntegerField(blank=True, db_column='locId', null=True)),
            ],
            options={
                'db_table': 'blocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locid', models.AutoField(db_column='locId', primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=10, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('metrocode', models.IntegerField(blank=True, db_column='metroCode', null=True)),
                ('areacode', models.IntegerField(blank=True, db_column='areaCode', null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('lng', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='ref_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Router'),
        ),
    ]
