# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edge',
            name='ref_node',
        ),
        migrations.AddField(
            model_name='edge',
            name='ref_node_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_node_1', to='map.Router'),
        ),
        migrations.AddField(
            model_name='edge',
            name='ref_node_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_node_2', to='map.Router'),
        ),
    ]
